### ISSUE TITLE
错误的vulkanalia版本

### ISSUE THREAD

**Issue by ILikeLayla** [chuigda/Vulkan-Tutorial-Rust-CN#93]
在“开发环境”当中 vulkanalia 的版本是 0.21.0
```toml
vulkanalia = { version = "=0.21.0", features = ["libloading", "provisional", "window"] }
```
但是现在英文版本是 0.23.0
```toml
vulkanalia = { version = "=0.23.0", features = ["libloading", "provisional", "window"] }
```

并且 0.21.0 版本没有支持bytecode modules, 这导致了 “14. 着色器模块” 的部分代码变得不可用， 因为该部分使用了bytecode modules
```rust
use vulkanalia::bytecode::Bytecode;
```
(这个在 0.21.0 版本会报错，找不到bytecode modules，但是在 0.23.0 可以正常运行)

**Comment by ILikeLayla** [comment]
希望这个项目还在维护吧

**Comment by chuigda** [comment]
Sorry, my badness. 我有空就去处理 QwQ

**Comment by chuigda** [comment]
Closed by https://github.com/chuigda/Vulkan-Tutorial-Rust-CN/commit/3385bccdb929a538cf72a78f5b5414069de4d187
